#! /bin/sh

error() {
    echo $*
    exit 2
}

http_servers="host"

if test $# -eq 1; then
    eid=$1
else
    for i in $http_servers
    do
        eid=`himage -e $i`
        if test $? -ne 0 ;then
            echo "Cannot find node $i"
            exit 2
        fi
    done
fi

himage host@$eid pkg info | grep "^lighttpd-" > /dev/null 2>&1
if test $? -ne 0 ;then
    echo "This example is based on lighttpd."
    echo "Please install package lighttpd and try again."
    exit 1
fi

for serv in $http_servers
do
    echo "Copying vulnerable bash to $serv"
    hcp bash.`uname -m` $serv:/usr/local/bin/bash
    echo "done."

    echo "Starting http server on $serv..."
    h=${serv}@${eid}
    himage $h mkdir -p /usr/local/etc/lighttpd
    himage $h mkdir -p /var/log/lighttpd
    himage $h chown -R www:www /var/log/lighttpd

    hcp ${serv}.lighttpd.conf $h:/usr/local/etc/lighttpd/lighttpd.conf
    himage $h chmod 755 /usr/local/etc/lighttpd/lighttpd.conf
    hcp -r www.${serv} $h:/root
    himage $h chmod +x /root/www.${serv}/form.sh
    himage $h lighttpd -f /usr/local/etc/lighttpd/lighttpd.conf
    echo "done."
done
