#! /bin/sh

http_servers="host"

for serv in $http_servers
do
    echo "Copying vulnerable bash to $serv"
    hcp bash.`uname -m` $serv:/usr/local/bin/bash
    echo "done."

    echo "Starting http server on $serv..."
    h=${serv}
    himage $h mkdir -p /usr/local/etc/lighttpd
    himage $h mkdir -p /var/log/lighttpd
    himage $h chown -R www:www /var/log/lighttpd

    hcp ${serv}.lighttpd.conf $h:/usr/local/etc/lighttpd/lighttpd.conf
    himage $h chmod 755 /usr/local/etc/lighttpd/lighttpd.conf
    hcp -r www.${serv} $h:/root
    himage $h chmod +x /root/www.${serv}/form.sh
    himage $h lighttpd -f /usr/local/etc/lighttpd/lighttpd.conf
    echo "done."
done
