#! /bin/sh

http_servers="www rogueServer"

for serv in $http_servers
do
    h=${serv}
    himage $h mkdir -p /usr/local/etc/lighttpd
    himage $h mkdir -p /var/log/lighttpd
    himage $h chown -R www:www /var/log/lighttpd

    hcp ${serv}.lighttpd.conf $h:/usr/local/etc/lighttpd/lighttpd.conf
    himage $h chmod 755 /usr/local/etc/lighttpd/lighttpd.conf
    hcp -r www.${serv} $h:/root
    himage $h lighttpd -f /usr/local/etc/lighttpd/lighttpd.conf
done
