#! /bin/sh

http_servers="host"

for serv in $http_servers
do
    himage $serv killall nginx
    echo "Starting https server on $serv..."
    h=${serv}
    hcp lighttpd.pem $h:/usr/local/nginx/conf/cert.pem
    hcp lighttpd.pem $h:/usr/local/nginx/conf/cert.key
    hcp ${serv}.nginx.conf $h:/usr/local/nginx/conf/nginx.conf
    hcp www.${serv}/* $h:/usr/local/nginx/html/
    himage $h /usr/local/nginx/sbin/nginx
done

#nmap -sV 10.0.0.10 --script ssl-heartbleed -d
#python heartbleed.py 10.0.0.10
